# A default configuration for TEN Host
#hostID:                   calculated
isGenesis:                 false
nodeType:                  "validator"
#hasClientRPCHTTP:         calculated
clientRPCPortHTTP:         80
#hasClientRPCWebsockets:   calculated
clientRPCPortWS:           81
clientRPCHost:             "127.0.0.1"
enclaveRPCAddresses:       ["127.0.0.1:11000"]
p2pBindAddress:            "0.0.0.0:10000"
p2pPublicAddress:          "127.0.0.1:10000"
l1WebsocketURL:            "ws://127.0.0.1:8546"
enclaveRPCTimeout:         10
l1RPCTimeout:              15
p2pConnectionTimeout:      10
managementContractAddress: ""
messageBusAddress:         ""
logLevel:                  3
logPath:                   "sys_out"
privateKey:                "0000000000000000000000000000000000000000000000000000000000000001"
l1ChainID:                 1337
tenChainID:                443
profilerEnabled:           false
l1StartHash:               ""
sequencerID:               ""
metricsEnabled:            true
metricsHTTPPort:           14000
useInMemoryDB:             true
postgresDBHost:            ""
sqliteDBPath:              ""
debugNamespaceEnabled:     false
batchInterval:             1
maxBatchInterval:          1
rollupInterval:            5
l1BlockTime:               15
isInboundP2PDisabled:      false
maxRollupSize:             65536 # 1024 * 64,