# A default configuration for TEN enclave

# Identity
hostID:                    ""
nodeType:                  "validator"

# Network configuration
managementContractAddress: ""
messageBusAddress:         ""
sequencerP2PAddress:       ""

# Service Settings
hostAddress:               "0.0.0.0:10000"
address:                   "0.0.0.0:11001"
willAttest:                false
validateL1Blocks:          false
useInMemoryDB:             false
edgelessDBHost:            ""
rpcTimeout:                5

# L2 Details
minGasPrice:               1 # 0 will use params.initialBaseFee
tenGenesis:                "{}"
l1ChainID:                 1337
tenChainID:                443
genesisJSON:               ""
gasLocalExecutionCap:      300_000_000_000

# Sequencer only
maxBatchSize:              56320 # 1024 * 36,
maxRollupSize:             65536 # 1024 * 64,
gasPaymentAddress:         "0xd6C9230053f45F873Cb66D8A02439380a37A4fbF"
gasBatchExecutionLimit:    300_000_000_000
l2BaseFee:                 0 # 0 will use params.initialBaseFee

# Extra Settings
logLevel:                  3
logPath:                   "sys_out"
profilerEnabled:           false
sqliteDBPath:              ""
debugNamespaceEnabled:     false