nodeAction: "start" # start | upgrade
nodeType: "validator" # sequencer | validator
isGenesis: false # must only be a single genesis node
isSGXEnabled: false # false for test (sgx simulation) not valid for live
enclaveDockerImage: "defaultEnclaveImage" # TEN provided
hostDockerImage: "defaultHostImage" # TEN provided
l1WebsocketURL: "ws://defaultnetwork:9000" # sepolia or mainnet node
hostP2PPort: 10000
hostP2PPublicAddr: "host.com:1000" # host ip or dns including port i.e. host.com:1000 (for external access whereas hostP2PPort may differ on VNET)
enclaveWSPort: 11001 # private internal ws port (sidecar/container or private VNET)
privateKey: "defaultKey" # private key associated with `hostID` public key, identity and rewards wallet for node
hostID: "defaultHostID" # public account key (match with privateKey)
sequencerID: "defaultSequencerID" # sequencer to send transactions
managementContractAddr: "defaultManagementAddr" # TEN provided
messageBusContractAddr: "defaultMessageBusAddr" # TEN provided
l1Start: "" # initial
pccsAddr: "" # SGX - Provisioning Certification Caching Service address
edgelessDBImage: "ghcr.io/edgelesssys/edgelessdb-sgx-4gb:v0.3.2"
hostHTTPPort: 80 # http port for external JSON-RPC requests from Gateway or custom proxy.
hostWSPort: 81 # ws port for external JSON-RPC requests from Gateway or custom proxy.
nodeName: "ten-node" # unique node-name, only used for internal-service routing and management (hostID is protocol ID)
isDebugNamespaceEnabled: false # activate debugging features, NOT FOR PRODUCTION
logLevel: 3 # logging
isInboundP2PDisabled: false # disable inboundP2P
batchInterval: "1s" # TEN provided - do not change should match sequencer
maxBatchInterval: "1s" # TEN provided - do not change should match sequencer
rollupInterval: "3s" # TEN provided - do not change should match sequencer
l1ChainID: 443 # TEN provided
profilerEnabled: false # go profiler
metricsEnabled: false # metrics
coinbaseAddress: "" # sequencer only
l1BlockTime: 15 # seconds per L1 block
tenGenesis: "{}" # genesis block
enclaveDebug: false # debug settings for enclave
hostInMemDB: true # whether to use in memory db for Node host or standalone db
hostExternalDBHost: "" # required when hostInMemDB false
hostExternalDBUser: ""
hostExternalDBPass: ""